update to 0.7.61

diff --git a/nginx.init b/nginx.init
--- a/nginx.init
+++ b/nginx.init
@@ -1,8 +1,8 @@
 #!/bin/sh
 #
-# nginx - this script starts and stops the nginx daemin
+# nginx - this script starts and stops the nginx daemon
 #
-# chkconfig:   - 85 15 
+# chkconfig:   - 85 15
 # description:  Nginx is an HTTP(S) server, HTTP(S) reverse \
 #               proxy and IMAP/POP3 proxy server
 # processname: nginx
@@ -41,7 +41,7 @@ start() {
 
 stop() {
     echo -n $"Stopping $prog: "
-    killproc $prog -QUIT
+    killproc $prog
     retval=$?
     echo
     [ $retval -eq 0 ] && rm -f $lockfile
@@ -49,25 +49,24 @@ stop() {
 }
 
 restart() {
-    configtest || return $?
+    configtest_q || configtest || return 6
     stop
     start
 }
 
 reload() {
-    configtest || return $?
+    configtest_q || configtest || return 6
     echo -n $"Reloading $prog: "
     killproc $nginx -HUP
-    RETVAL=$?
     echo
-}
-
-force_reload() {
-    restart
 }
 
 configtest() {
   $nginx -t -c $NGINX_CONF_FILE
+}
+
+configtest_q() {
+    configtest >/dev/null 2>&1
 }
 
 rh_status() {
@@ -76,6 +75,29 @@ rh_status() {
 
 rh_status_q() {
     rh_status >/dev/null 2>&1
+}
+
+# Upgrade the binary with no downtime.
+upgrade() {
+    local pidfile="/var/run/${prog}.pid"
+    local oldbin_pidfile="${pidfile}.oldbin"
+
+    configtest_q || configtest || return 6
+    echo -n $"Staring new master $prog: "
+    killproc $nginx -USR2
+    retval=$?
+    echo 
+    sleep 1
+    if [[ -f ${oldbin_pidfile} && -f ${pidfile} ]];  then
+        echo -n $"Graceful shutdown of old $prog: "
+        killproc -p ${oldbin_pidfile} -QUIT
+        retval=$?
+        echo 
+        return 0
+    else
+        echo $"Something bad happened, manual intervention required, maybe restart?"
+        return 1
+    fi
 }
 
 case "$1" in
@@ -90,20 +112,22 @@ case "$1" in
     restart|configtest)
         $1
         ;;
+    force-reload|upgrade) 
+        rh_status_q || exit 7
+        upgrade
+        ;;
     reload)
         rh_status_q || exit 7
         $1
         ;;
-    force-reload)
-        force_reload
-        ;;
-    status)
-        rh_status
+    status|status_q)
+        rh_$1
         ;;
     condrestart|try-restart)
-        rh_status_q || exit 0
+        rh_status_q || exit 7
+        restart
 	    ;;
     *)
-        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload|configtest}"
+        echo $"Usage: $0 {start|stop|reload|configtest|status|force-reload|upgrade|restart}"
         exit 2
 esac
